In [2]:
import tensorflow as tf
import numpy as np
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load it from Faster RCNN

In [3]:
from od.model.faster_rcnn import FasterRcnnFPNResnet50

model =  FasterRcnnFPNResnet50(80)
image_information = tf.constant([[200, 200], [200, 200]])
features = tf.zeros((2, 325, 325, 3))

output = model({'images': features, 'images_information': image_information})


In [24]:
class A:
    def __init__(self):
        self._trainable = False
        self._image = 'image'
        self._a_layer = 'a_layer'
        self._trainable = 'trainable'
        
    @property
    def trainable(self):
        return self._trainable
    
    @trainable.setter
    def trainable(self, value):
        self._trainable = value
        for layer in getattr(self, '_layers', []):
            layer = value

        
        

In [25]:
test = A()

getattr(test, '_layers', [])

[]

# Proof that a kernel in channels first or channels last is the same

In [22]:
import numpy as np
import tensorflow as tf

cl = tf.keras.layers.Conv2D(3, 3, data_format='channels_last')
inputs = np.arange(4 * 4 * 3).reshape(1, 4, 4, 3).astype(np.float32)
cl_out = cl(inputs)
cl_weights = cl.get_weights()

inputs_cf = np.moveaxis(inputs, -1, 1)
cf = tf.keras.layers.Conv2D(3, 3, data_format='channels_first')
out_before_weigths = cf(inputs_cf)
cf.set_weights(cl_weights)
out_after_weights =cf(inputs_cf)
np.testing.assert_array_equal(cf.get_weights()[0], cl.get_weights()[0])
np.testing.assert_array_equal(out_after_weights.numpy(), np.moveaxis(cl_out.numpy(), -1, 1))

UnimplementedError: The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW [Op:Conv2D]

array([[[[ 0.,  3.,  6.,  9., 12.],
         [15., 18., 21., 24., 27.],
         [30., 33., 36., 39., 42.],
         [45., 48., 51., 54., 57.],
         [60., 63., 66., 69., 72.]],

        [[ 1.,  4.,  7., 10., 13.],
         [16., 19., 22., 25., 28.],
         [31., 34., 37., 40., 43.],
         [46., 49., 52., 55., 58.],
         [61., 64., 67., 70., 73.]],

        [[ 2.,  5.,  8., 11., 14.],
         [17., 20., 23., 26., 29.],
         [32., 35., 38., 41., 44.],
         [47., 50., 53., 56., 59.],
         [62., 65., 68., 71., 74.]]]], dtype=float32)

In [20]:
value_before_loading_weights = {}
for var in model.resnet.variables:
    value_before_loading_weights[var.name] = var.numpy()

In [21]:
model.resnet.load_weights('resnet50_tensorpack_converted.h5', by_name=True)

In [22]:
value_after_loading_weights = {}
for var in model.resnet.variables:
    value_after_loading_weights[var.name] = var.numpy()

In [23]:
for i,key in enumerate(value_before_loading_weights.keys()):
    try:
        np.testing.assert_array_equal(value_before_loading_weights[key],
                              value_after_loading_weights[key])
    except AssertionError:
        error =True
    
    if not error:
        raise Exception

In [16]:
print(i)

264


In [ ]:
np.testing.assert_

In [21]:
model.resnet.groups[0].variables

[<tf.Variable 'resnet50/group0/block0/convshortcut/kernel:0' shape=(1, 1, 64, 256) dtype=float32, numpy=
 array([[[[ 0.06565944, -0.05118347, -0.14900146, ..., -0.03274954,
           -0.0214356 ,  0.02626163],
          [-0.1337028 ,  0.01506449,  0.0147299 , ..., -0.06182129,
            0.00743022,  0.00704191],
          [ 0.07241719, -0.05308066, -0.15391132, ...,  0.01020731,
           -0.06713594,  0.01650506],
          ...,
          [ 0.05168343, -0.0959791 , -0.05579475, ..., -0.07898179,
           -0.0624295 ,  0.00234917],
          [-0.02255951, -0.0621385 , -0.03245717, ...,  0.01000376,
           -0.02024606, -0.46684086],
          [-0.07193648,  0.01522338, -0.0358327 , ..., -0.0734093 ,
           -0.03483985,  0.03155651]]]], dtype=float32)>,
 <tf.Variable 'resnet50/group0/block0/convshortcut/bn/gamma:0' shape=(256,) dtype=float32, numpy=
 array([1.9452529e+00, 1.7117873e+00, 2.7982886e+00, 1.5358564e+00,
        8.8594288e-01, 1.3780795e+00, 9.8034626e-01, 1.097

## Test2

In [23]:
def image_preprocess(image, bgr=True):

    # TODO check the inputs
    mean = [123.675, 116.28, 103.53]
    std = [58.395, 57.12, 57.375]
    if bgr:
        mean = mean[::-1]
        std = std[::-1]
    image_mean = tf.constant(mean, dtype=image.dtype)
    image_invstd = tf.constant(1.0 / std, dtype=image.dtype)
    image = (image - image_mean) * image_invstd
    return image

In [5]:
mean = np.array([123.675, 116.28, 103.53])
std = np.array([58.395, 57.12, 57.375])
mean = mean[::-1]
std = std[::-1]

array([57.375, 57.12 , 58.395])

In [27]:
image_preprocess(test)

TypeError: unsupported operand type(s) for /: 'float' and 'list'