In [41]:
import tensorflow as tf
from scipy.optimize import linear_sum_assignment
import numpy as np

In [213]:
test = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.gather(test, [[[0, 1]], [[1, 2]]])

InvalidArgumentError: indices[1,0,1] = 2 is not in [0, 2) [Op:GatherV2]

In [57]:
hungarian_func(test[0])

InvalidArgumentError: TypeError: <lambda>() takes 1 positional argument but 4 were given
Traceback (most recent call last):

  File "/home/egarreau/.pyenv/versions/3.7.2/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 241, in __call__
    return func(device, token, args)

  File "/home/egarreau/.pyenv/versions/3.7.2/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 130, in __call__
    ret = self._func(*args)

  File "/home/egarreau/.pyenv/versions/3.7.2/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

TypeError: <lambda>() takes 1 positional argument but 4 were given

 [Op:EagerPyFunc]

In [ ]:
lambda cost_matrix: tf.py_function(self.call, [arg], Tout=[tf.float32, tf.float32]),


In [63]:
test[0]

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1.e+00, 2.e+00, 3.e+00, 5.e-01],
       [4.e+00, 5.e+00, 6.e+00, 2.e+00],
       [8.e+00, 4.e+00, 4.e+00, 3.e+00],
       [1.e+03, 1.e+03, 1.e+03, 1.e+03]], dtype=float32)>

In [69]:
from kerod.utils import get_full_indices

In [117]:
test = [[[1, 2, 3, 0.5,], [4, 5, 6, 2], [8, 4, 4, 3]],[[1, 2, 3, 0.5], [4, 5, 6, 2], [8, 4, 4, 3]]]
test = tf.constant(test)

func = lambda cost_matrix: tf.py_function(lambda c: linear_sum_assignment(c)[1],
                                [cost_matrix],
                                Tout=tf.float32)
indices = tf.map_fn(func, -test)

In [201]:
matches = tf.one_hot(tf.cast(indices, tf.int32), 4)
final_matches = tf.reduce_max(matches * indices[..., None], axis=1)
final_matches

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 1., 2., 0.],
       [0., 1., 2., 0.]], dtype=float32)>

In [202]:
masked_boxes = tf.where(indices == [[2], [3]], -1, 1)
full_indices = get_full_indices(tf.cast(indices, tf.int32))
weights = tf.scatter_nd(full_indices, masked_boxes, (2, 4))

In [203]:
positive_weights

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 0.],
       [1., 1., 1., 0.]], dtype=float32)>

In [195]:
matches

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.]]], dtype=float32)>

In [151]:
tf.scatter_nd()

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 1., 2., 0.],
       [0., 1., 2., 0.]], dtype=float32)>

In [ ]:
final_weights = [[-1, 1, 1, 0],[1, 1, 1, 0]]

In [169]:
final_matches


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 1., 2., 0.],
       [0., 1., 2., 0.]], dtype=float32)>

In [170]:
indices

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 1., 0.],
       [2., 1., 0.]], dtype=float32)>

In [177]:
tf.tile(tf.range(4)[None], [2, 1])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int32)>