In [106]:
import numpy as np
import tensorflow as tf

/home/egarreau/.pyenv/versions/3.6.6/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


False

In [108]:
test = np.array([4, 5])
tf.sequence_mask(
     test, dtype=tf.dtypes.bool, name=None
)


<tf.Tensor: shape=(2, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])>

In [110]:
test = np.array([[[0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]],

       [[0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [1, 1, 1, 1, 1]]], dtype=bool)

In [113]:
num_valid_boxes = np.array([3, 3])
mask_valid_boxes = tf.sequence_mask(
     num_valid_boxes, maxlen=4, dtype=tf.bool
)

In [126]:
300000/200/60

25.0

In [119]:
tf.math.logical_and(test, mask_valid_boxes[:, :, None])

<tf.Tensor: shape=(2, 4, 5), dtype=bool, numpy=
array([[[False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False,  True, False],
        [False, False, False, False, False]],

       [[False, False, False,  True, False],
        [ True, False, False, False, False],
        [False, False, False, False,  True],
        [False, False, False, False, False]]])>

In [127]:
mask_valid_boxes[0, 0] = False

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [128]:
not None

True